### ISSUE TITLE
Error on new troops after a raid

### ISSUE THREAD

**Issue by Stoakes** [yi12345/TravianT4#63]
I send some raids on Multihunter's village, sometimes i saw my troops being multiplied after they came back.
It happened twice : 
Send 2 troops (legionaires), got 4 after the arrival
Send 4 troops (legionaires), got 12 after the arrival.

I checked GameEngine/Units.php  but didn't see where it might came from.

**Comment by cosme12** [comment]
Are you sure those bugs happen because you are using/attacking multihunter village?

**Comment by Stoakes** [comment]
Oh sorry i didn't delete this topic while it was solved. Because the civilization (romans,teutons..) of the Multihunter is 0, it is bugging.

**Comment by cosme12** [comment]
Oh someone at least is here. I tought this proyect was dead. It didnt recive any answers since a long time ago.
